### ISSUE TITLE
train.py fails on 2013 MBP, no CUDA

### ISSUE THREAD

**Issue by neilyoung** [nianticlabs/monodepth2#113]
I know I don't have a CUDA capable device, but the only disadvantage I know about not having CUDA is that it would take 100x longer (from another thread).

Tried that (not seriously) on my Mac, got this error:

```
(monodepth2) ~/Documents/monodepth2 $ python train.py --model_name mono_model
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /Users/decades/.torch/models/resnet18-5c106cde.pth
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 46827520/46827520 [00:08<00:00, 5745578.32it/s]
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    trainer = Trainer(opts)
  File "/Users/decades/Documents/monodepth2/trainer.py", line 56, in __init__
    self.models["encoder"].to(self.device)
  File "/Users/decades/opt/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 379, in to
    return self._apply(convert)
  File "/Users/decades/opt/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/Users/decades/opt/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/Users/decades/opt/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/Users/decades/opt/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 377, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.

```

**Comment by neilyoung** [comment]
torch.cuda.is_available() delivers False on this machine. Surely that's why.

Maybe this helps. https://discuss.pytorch.org/t/cannot-initialize-cuda-without-aten-cuda-library/24745/5

**Comment by neilyoung** [comment]
`python train.py --model_name mono_model --no_cuda`

It launched, but misses a KITTI JPG file

`No such file or directory: '/Users/decades/Documents/monodepth2/kitti_data/2011_09_30/2011_09_30_drive_0028_sync/image_02/data/0000001114.jpg'`

**Comment by mrharicot** [comment]
Hi,
Did you verify that this file exists?
