### ISSUE TITLE
CUDA ERROR:Out of memory

### ISSUE THREAD

**Issue by Rishika-Sai** [nianticlabs/monodepth2#155]
FAIL file=..\aten\src\THC\THCCachingHostAllocator.cpp line=271 error=2 : out of memory
My System has NIVIDIA GTX1050 ti

when I run train file
D:\Anaconda3\Project>python train.py --model_name mono_model --png
Training model named:
   mono_model
Models and tensorboard events files are saved to:
   C:\Users\Anusha_Bandaru\tmp
Training is using:
   cuda
Using split:
   eigen_zhou
There are 37782 training items and 4424 validation items

Training
THCudaCheck FAIL file=..\aten\src\THC\THCCachingHostAllocator.cpp line=271 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    trainer.train()
  File "D:\Anaconda3\Project\trainer.py", line 191, in train
    self.run_epoch()
  File "D:\Anaconda3\Project\trainer.py", line 203, in run_epoch
    for batch_idx, inputs in enumerate(self.train_loader):
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 133, in _worker_manager_loop
    batch = pin_memory_batch(batch)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 198, in pin_memory_batch
    return {k: pin_memory_batch(sample) for k, sample in batch.items()}
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 198, in <dictcomp>
    return {k: pin_memory_batch(sample) for k, sample in batch.items()}
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 194, in pin_memory_batch
    return batch.pin_memory()
RuntimeError: cuda runtime error (2) : out of memory at ..\aten\src\THC\THCCachingHostAllocator.cpp:271

**Comment by mrharicot** [comment]
Hi,
The 1050Ti typically only has 4GB of memory, you should reduce the batch size to make sure it fits onto the GPU.
