### ISSUE TITLE
 pth to pt has a problem

### ISSUE THREAD

**Issue by psw13583112** [nianticlabs/monodepth2#177]
Traceback (most recent call last):
  File "depth.py", line 140, in <module>
    depth_jit = torch.jit.script(depth_model) 
  File "/data/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 1255, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/data/anaconda3/lib/python3.6/site-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/data/anaconda3/lib/python3.6/site-packages/torch/jit/_recursive.py", line 293, in create_script_module
    concrete_type = concrete_type_store.get_or_create_concrete_type(nn_module)
  File "/data/anaconda3/lib/python3.6/site-packages/torch/jit/_recursive.py", line 236, in get_or_create_concrete_type
    concrete_type_builder = infer_concrete_type_builder(nn_module)
  File "/data/anaconda3/lib/python3.6/site-packages/torch/jit/_recursive.py", line 121, in infer_concrete_type_builder
    sub_concrete_type = concrete_type_store.get_or_create_concrete_type(item)
  File "/data/anaconda3/lib/python3.6/site-packages/torch/jit/_recursive.py", line 236, in get_or_create_concrete_type
    concrete_type_builder = infer_concrete_type_builder(nn_module)
  File "/data/anaconda3/lib/python3.6/site-packages/torch/jit/_recursive.py", line 198, in infer_concrete_type_builder
    attr_type = infer_type(name, value)
  File "/data/anaconda3/lib/python3.6/site-packages/torch/jit/_recursive.py", line 83, in infer_type
    attr_type = torch._C._jit_try_infer_type(item)
RuntimeError: Cannot create dict for key type '(str, int)', only int, float, Tensor and string keys are supported (create at /pytorch/aten/src/ATen/core/jit_type.h:691)

Problems with parsing DepthDecoder

**Comment by mrharicot** [comment]
Hi,
as you can see from the error message:
```
RuntimeError: Cannot create dict for key type '(str, int)', only int, float, Tensor and string keys are supported (create at /pytorch/aten/src/ATen/core/jit_type.h:691)
```
Using `(str, int)` keys for the layers is not supported when trying to serialize the model. You could replace the `("upconv", i, 0)` by `"upconv_{}_{}".format(i, 0)` for instance.

**Comment by psw13583112** [comment]
> 嗨，
> 您会从错误消息中看到：
> 
> ```
> RuntimeError: Cannot create dict for key type '(str, int)', only int, float, Tensor and string keys are supported (create at /pytorch/aten/src/ATen/core/jit_type.h:691)
> ```
> 
> `(str, int)`尝试序列化模型时，不支持为图层使用键。你可以更换`("upconv", i, 0)`的`"upconv_{}_{}".format(i, 0)`，例如。


Thank you for your answer. After solving the above, there is a new problem，“ Module 'DepthDecoder' has no attribute 'convs' (This attribute exists on the Python module, but we failed to convert Python type: 'OrderedDict' to a TorchScript type.) “， Can it only be modified into a structure that is not a dictionary

**Comment by psw13583112** [comment]
> Hi,
> as you can see from the error message:
> 
> ```
> RuntimeError: Cannot create dict for key type '(str, int)', only int, float, Tensor and string keys are supported (create at /pytorch/aten/src/ATen/core/jit_type.h:691)
> ```
> 
> Using `(str, int)` keys for the layers is not supported when trying to serialize the model. You could replace the `("upconv", i, 0)` by `"upconv_{}_{}".format(i, 0)` for instance.



Thank you very much for your reply,I successfully run
