### ISSUE TITLE
Run test_simple.py error

### ISSUE THREAD

**Issue by liubron** [nianticlabs/monodepth2#186]
Hello,

I used cuda 9.1 and pytorch 0.4.0 on win10 platform to run test_simple.py, but I got a error is:
TypeError: 'torch.Device' object is not callable,
Do you know how TO solve it?

**Comment by mrharicot** [comment]
Hi,
Could you share the entire error message?

**Comment by liubron** [comment]
ok,thanks for your reply, the error is as follows:

Traceback (most recent call last):
  File "F:/depth/monodepth2-master/monodepth2-master/test_simple.py", line 155, in <module>
    test_simple(args)
  File "F:/depth/monodepth2-master/monodepth2-master/test_simple.py", line 73, in test_simple
    loaded_dict_enc = torch.load(encoder_path, map_location=device)
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 469, in _load
    result = unpickler.load()
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 323, in restore_location
    result = map_location(storage, location)
TypeError: 'torch.Device' object is not callable

**Comment by mrharicot** [comment]
Thanks, can you also share the command you ran?

**Comment by liubron** [comment]
ok,I run this code in win10
test_simple.py --image_path F:/dataset/1.jpg  --model_name mono+stereo_640x192

**Comment by mrharicot** [comment]
It seems that your GPU isn't found by the code as this issue happens if pytorch is trying to load the weights to the CPU. 
There is a bug in pytorch 0.4.0, you could update to 0.4.1 to fix it or you can [edit line 73](https://github.com/nianticlabs/monodepth2/blob/master/test_simple.py#L73):
```python
loaded_dict_enc = torch.load(encoder_path, map_location='cpu')
```

Can you verify that it finds the gpu by adding this on L63:
```python
print(device)
```

**Comment by liubron** [comment]
The output of 'print(device)' is cuda.
and I modified L73 as your advice, but I got the same error before.
maybe I should update my pytorch version to 0.4.1

**Comment by mrharicot** [comment]
Interesting. Can you modify Line 73 as follows?
```python
loaded_dict_enc = torch.load(encoder_path, map_location='cuda')
```

**Comment by liubron** [comment]
The error was changed.

Traceback (most recent call last):
  File "F:/depth/monodepth2-master/monodepth2-master/test_simple.py", line 157, in <module>
    test_simple(args)
  File "F:/depth/monodepth2-master/monodepth2-master/test_simple.py", line 75, in test_simple
    loaded_dict_enc = torch.load(encoder_path, map_location='cuda')
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 469, in _load
    result = unpickler.load()
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 320, in restore_location
    return default_restore_location(storage, map_location)
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 88, in default_restore_location
    result = fn(storage, location)
  File "D:\anaconda\lib\site-packages\torch\serialization.py", line 69, in _cuda_deserialize
    device = max(int(location[5:]), 0)
ValueError: invalid literal for int() with base 10: ''

**Comment by liubron** [comment]
I have updated my pytorch to 0.4.1, and the problem was solved!
Thank you for your help.
