### ISSUE TITLE
Failed to train on a part of kitti raw data

### ISSUE THREAD

**Issue by wbzhang233** [nianticlabs/monodepth2#323]
Hey Dear Author, I wanna train this model under a part of kitti raw data cause' my xavier don't have enough storage for the whole. When I try to train this model with my RTX3090 GPU, the error occured.
```
Using split:
   mine
There are 1464 training items and 401 validation items

Training
Traceback (most recent call last):
  File "/home/wbzhang/monodepth2/train.py", line 18, in <module>
    trainer.train()
  File "/home/wbzhang/monodepth2/trainer.py", line 190, in train
    self.run_epoch()
  File "/home/wbzhang/monodepth2/trainer.py", line 202, in run_epoch
    for batch_idx, inputs in enumerate(self.train_loader):
  File "/home/wbzhang/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/wbzhang/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/wbzhang/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/wbzhang/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wbzhang/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wbzhang/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wbzhang/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wbzhang/monodepth2/datasets/mono_dataset.py", line 182, in __getitem__
    self.preprocess(inputs, color_aug)
  File "/home/wbzhang/monodepth2/datasets/mono_dataset.py", line 109, in preprocess
    inputs[(n + "_aug", im, i)] = self.to_tensor(color_aug(f))
TypeError: 'tuple' object is not callable


Process finished with exit code 1
```

My conda environment like below.
```
(monodepth2) wbzhang@ps:~/monodepth2$ conda list
# packages in environment at /home/wbzhang/anaconda3/envs/monodepth2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                      1_llvm    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
backcall                  0.2.0                     <pip>
ca-certificates           2020.12.5            ha878542_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
certifi                   2020.12.5        py36h5fab9bb_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cffi                      1.14.5           py36hc120d54_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cudatoolkit               10.2.89              h8f6ccaa_8    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cudnn                     7.6.5.32             h01f27c4_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cycler                    0.10.0                    <pip>
dataclasses               0.8                pyh787bdff_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
decorator                 4.4.2                     <pip>
future                    0.18.2           py36h5fab9bb_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
imageio                   2.9.0                     <pip>
ipython                   7.16.1                    <pip>
ipython-genutils          0.2.0                     <pip>
jedi                      0.18.0                    <pip>
kiwisolver                1.3.1                     <pip>
ld_impl_linux-64          2.33.1               h53a641e_7  
libblas                   3.9.0                     8_mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libcblas                  3.9.0                     8_mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h2828fa1_18    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
liblapack                 3.9.0                     8_mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
llvm-openmp               11.0.1               h4bd325d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
magma                     2.5.4                h7384022_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
matplotlib                3.3.4                     <pip>
mkl                       2020.4             h726a3e6_304    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nccl                      2.8.4.1              h1a5f58c_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ncurses                   6.2                  he6710b0_1  
networkx                  2.5                       <pip>
ninja                     1.10.2               h4bd325d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
numpy                     1.19.5           py36h2aa4a07_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
openssl                   1.1.1j               h7f98852_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
parso                     0.8.1                     <pip>
pexpect                   4.8.0                     <pip>
pickleshare               0.7.5                     <pip>
Pillow                    8.1.2                     <pip>
pip                       21.0.1           py36h06a4308_0  
prompt-toolkit            3.0.17                    <pip>
protobuf                  3.15.6                    <pip>
ptyprocess                0.7.0                     <pip>
pycparser                 2.20               pyh9f0ad1d_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
Pygments                  2.8.1                     <pip>
pyparsing                 2.4.7                     <pip>
python                    3.6.13               hdb3f193_0  
python-dateutil           2.8.1                     <pip>
python_abi                3.6                     1_cp36m    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch                   1.7.1           cuda102py36h8620ce9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch-cpu               1.6.0           cpu_py36h3ab7d31_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch-gpu               1.7.1           cuda102py36hf05f184_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
PyWavelets                1.1.1                     <pip>
readline                  8.1                  h27cfd23_0  
scikit-image              0.17.2                    <pip>
scipy                     1.5.4                     <pip>
setuptools                52.0.0           py36h06a4308_0  
six                       1.15.0                    <pip>
sqlite                    3.33.0               h62c20be_0  
tensorboardX              2.1                       <pip>
tifffile                  2020.9.3                  <pip>
tk                        8.6.10               hbc83047_0  
torch                     1.8.0                     <pip>
torchvision               0.9.0                     <pip>
traitlets                 4.3.3                     <pip>
typing_extensions         3.7.4.3                    py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wcwidth                   0.2.5                     <pip>
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```

Thank you!

**Comment by oconnor127** [comment]
Got the same error. It occurs when training on GPU as well as on CPU. I followed exactly your readMe and downloaded the entire kitti dataset to train the net with it.

**Comment by oconnor127** [comment]
You got an error in mono_dataset.py. When calling the function "self.preprocess", images might have different sizes. However, to solve this problem in a cheap way you can set line 140 ("do_color_aug = self.is_train and ..") to do_color_aug = False (for everyone who is facing the same problem). Are the authors solving this problem?

**Comment by h8c2** [comment]
set line 178   **color_aug = transforms.ColorJitter( self.brightness, self.contrast, self.saturation, self.hue)**  instead of **color_aug = transforms.ColorJitter.get_params( self.brightness, self.contrast, self.saturation, self.hue)**

**Comment by wbzhang233** [comment]
> set line 178 **color_aug = transforms.ColorJitter( self.brightness, self.contrast, self.saturation, self.hue)** instead of **color_aug = transforms.ColorJitter.get_params( self.brightness, self.contrast, self.saturation, self.hue)**

Thank you very much!

**Comment by adizhol** [comment]
@h8c2 @wbzhang233 @daniyar-niantic 
won't this cause the preprocessing to augment each frame [0,1,-1] differently?

**Comment by akashchavan15** [comment]
Is this issue solved? 
@adizhol Did you get answer to your question?

**Comment by adizhol** [comment]
> Is this issue solved? @adizhol Did you get answer to your question?

I ended up using albumentation transforms + replay

**Comment by JonasKonrad** [comment]
@adizhol  Btw, late reply, but that's absolutely correct (for newer versions of torchvision > [0.8.2](https://github.com/pytorch/vision/blob/v0.8.2/torchvision/transforms/transforms.py)).
From my point of view, best is to manually resemble the old torchvision.transforms.ColorJitter.get_params() behavior (constructing a torchvision.transforms.Compose with torchvision.transforms.Lambda()). You'll get the specific parameters from the function get_params(), which now is a static function actually doing what it should (providing you with uniformly sampled parameters instead of manipulating the image already). Now, you can apply those parameters in the resembled get_params(), take a look at the **current**  torchvision.transforms.ColorJitter.forward() function also, to see how to apply the single transforms of the composed one in the correct order.
