### ISSUE TITLE
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device...

### ISSUE THREAD

**Issue by andersonhusky** [nianticlabs/monodepth2#354]
I just used the pre-trained mono+stereo model and I got thist error:
"THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=663 error=8 : invalid device function
Traceback (most recent call last):
  File "test_simple.py", line 171, in <module>
    test_simple(args)
  File "test_simple.py", line 132, in test_simple
    features = encoder(input_image)
  File "/home/hongfeng/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hongfeng/monodepth2/networks/resnet_encoder.py", line 92, in forward
    self.features.append(self.encoder.relu(x))
  File "/home/hongfeng/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hongfeng/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 46, in forward
    return F.threshold(input, self.threshold, self.value, self.inplace)
  File "/home/hongfeng/anaconda3/envs/monodepth2/lib/python3.6/site-packages/torch/nn/functional.py", line 624, in threshold
    return torch._C._nn.threshold_(input, threshold, value)
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THCUNN/generic/Threshold.cu:34
"

**Comment by mdfirman** [comment]
Hi, thanks for your interest.

Can you run any other torch programs?

e.g. does the following run:
```
import torch
torch.cuda.is_available()
torch.tensor([1.0, 2.0])
torch.tensor([1.0, 2.0]).cuda()
```

If not – then it looks like you have a torch install problem, which is outside the scope of this repo. See here for some advice: https://github.com/pytorch/pytorch/issues/31285

**Comment by mdfirman** [comment]
I'm going to close this as it seems outside our scope. Reopen if needed, thanks.
