### ISSUE TITLE
NoneType

### ISSUE THREAD

**Issue by xanmolx** [nianticlabs/monodepth2#403]
```
Traceback (most recent call last):
  File "/Users/anmolsinghsethi/opt/anaconda3/envs/temp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
  File "/Users/anmolsinghsethi/opt/anaconda3/envs/temp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
  File "/Users/anmolsinghsethi/opt/anaconda3/envs/temp/lib/python3.6/multiprocessing/queues.py", line 337, in get
TypeError: 'NoneType' object is not callable
```

I did the exact same steps as in readme. 

Getting the above error when I run this:-
```
python  train.py --model_name mono_model --no_cuda --split eigen_full
```

**Comment by daniyar-niantic** [comment]
Hi. Have you installed correct pytorch and torchvision versions?

**Comment by daniyar-niantic** [comment]
Also, have you downloaded Kitti dataset? The NoneType error could be due to missing/inaccessible files.

**Comment by daniyar-niantic** [comment]
Closing due to lack of update
