### ISSUE TITLE
Training for tiny KITTI dataset

### ISSUE THREAD

**Issue by luda1013** [nianticlabs/monodepth2#410]
Hallo all,

because the KITTI Dataset is too big(175GB) , i download the tiny version of it. i got it from here:
https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/datasets/DDAD_tiny.tar

 i unzipped and save its content in kitty_data
 
 when i ran the train.py under conda environment:
python train.py --model_name mono_model

;i got the following error:

(monodepth2) luda1013@luda1013-VirtualBox:~$ python train.py --model_name mono_model
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from trainer import Trainer
  File "/home/luda1013/trainer.py", line 26, in <module>
    from IPython import embed
  File "/home/luda1013/anaconda3/envs/monodepth2/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/luda1013/anaconda3/envs/monodepth2/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/luda1013/anaconda3/envs/monodepth2/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/home/luda1013/anaconda3/envs/monodepth2/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/home/luda1013/anaconda3/envs/monodepth2/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/home/luda1013/anaconda3/envs/monodepth2/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/luda1013/anaconda3/envs/monodepth2/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
    import parso
  File "/home/luda1013/anaconda3/envs/monodepth2/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/home/luda1013/anaconda3/envs/monodepth2/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

had anyone the same problem with me? or can someone help me in this matter? thanks a lot :)

**Comment by daniyar-niantic** [comment]
Hi. Are you using correct python/pytorch/torchvision version?

**Comment by daniyar-niantic** [comment]
Closing due to missing details.
