### ISSUE TITLE
Training on own dataset: RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:411

### ISSUE THREAD

**Issue by Donkey1123** [nianticlabs/monodepth2#81]
Hi,
I collected some data for training and I got the following errors. Basically, I create a new dataset loader inherited from monodataset and create a new split method for my dataset. Please help me resolve this issue. Many thanks in advance.
My env are:
python: 3.6
cudatoolkit: 9.0    
pytorch: 0.4.1    
The error message is:
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
Traceback (most recent call last):
  File "/home/air/pycharm-2019.2.2/helpers/pydev/pydevd.py", line 2066, in <module>
    main()
  File "/home/air/pycharm-2019.2.2/helpers/pydev/pydevd.py", line 2060, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/air/pycharm-2019.2.2/helpers/pydev/pydevd.py", line 1411, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/air/pycharm-2019.2.2/helpers/pydev/pydevd.py", line 1418, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/air/pycharm-2019.2.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/air/新加卷/downloads/monodepth2/train.py", line 18, in <module>
    trainer.train()
  File "/media/air/新加卷/downloads/monodepth2/trainer.py", line 190, in train
    self.run_epoch()
  File "/media/air/新加卷/downloads/monodepth2/trainer.py", line 206, in run_epoch
    outputs, losses = self.process_batch(inputs)
  File "/media/air/新加卷/downloads/monodepth2/trainer.py", line 256, in process_batch
    outputs.update(self.predict_poses(inputs, features))
  File "/media/air/新加卷/downloads/monodepth2/trainer.py", line 296, in predict_poses
    axisangle[:, 0], translation[:, 0], invert=(f_i < 0))
  File "/media/air/新加卷/downloads/monodepth2/layers.py", line 41, in transformation_from_parameters
    M = torch.matmul(R, T)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:411

**Comment by mdfirman** [comment]
Hi @Donkey1123 , thanks for your interest.

Can you verify that the values that your custom dataloader returns are all of equivalent shape and type that the kitti loader returns? This is the most likely source of error.

**Comment by Donkey1123** [comment]
@mdfirman  Thanks for your quick response. This following code is my dataloader. Is it accurate? I followed the instruction and only changed the return of check_depth to "return False". My input image size is 256*256 and it's temporal images sliced from videos. Also, I only label my data in train.txt/test.txt as ''folder index l" and I don't have r images.

What self.K and self.side_map stand for?

Thanks again.

class indoorDataset(MonoDataset):
    def __init__(self, *args, **kwargs):
        super(indoorDataset, self).__init__(*args, **kwargs)

        self.K = np.array([[0.58, 0, 0.5, 0],
                           [0, 1.92, 0.5, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]], dtype=np.float32)

        self.full_res_shape = (1242, 375)
        self.side_map = {"2": 2, "3": 3, "l": 2, "r": 3}

    def check_depth(self):
        line = self.filenames[0].split()
        scene_name = line[0]
        frame_index = line[1]

        velo_filename = os.path.join(
            self.data_path,
            scene_name,
            "velodyne_points/data/{}.bin".format(frame_index))
        return False

    def get_image_path(self, folder, frame_index, side):
        print('frame_index: ', frame_index)
        f_str = "%07d%s" % (frame_index, self.img_ext)
        image_path = os.path.join(
            self.data_path, folder, f_str)
        return image_path

    def get_color(self, folder, frame_index, side, do_flip):
        color = self.loader(self.get_image_path(folder, frame_index, side))
        if do_flip:
            color = color.transpose(pil.FLIP_LEFT_RIGHT)

        return color

**Comment by daniyar-niantic** [comment]
`self.K` is intrinsics matrix estimated from [camera calibration](https://docs.opencv.org/3.4/d4/d94/tutorial_camera_calibration.html). You can ignore `self.side_map`, it is only used for training with KITTI.

Are you sure you are always loading 3 frames when training?

**Comment by dongfangliu66** [comment]
@daniyar-niantic Thanks for your help. How do I know I successfully load 3 frames?

Also, should I change self.full_res_shape = (1242, 375) to my input image size?

Thank you!

**Comment by mdfirman** [comment]
You can check your outputs by adding some print statements to your code. Just before [this line](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py#L200)  try adding something like:
```
for key, value in inputs.items():
    print(key, value.shape)
```
Then you will get printed to screen what the shapes are for your data, and also for the kitti dataset when you train on that. I would verify that these are giving the same shapes. 

Don't worry about the value of `full_res_shape` if `check_depth` is always False, as `full_res_shape`  will not be used.

**Comment by daniyar-niantic** [comment]
@dongfangliu66 Have you managed to resolve your issue?

**Comment by daniyar-niantic** [comment]
I assume you have resolved the issue.
