### ISSUE TITLE
training on my own dataset

### ISSUE THREAD

**Issue by kou5321** [nianticlabs/monodepth2#86]
Hi! 
I want to train the model on my own dataset. And I have written the own split as well as  creating a new dataset subclassing from MonoDataset. The dataset is a monocular video, and it was cut every 3 frames.

Part of my_custm_split is that 
urpc/urpc1 4 l
urpc/urpc1 7 l
urpc/urpc1 10 l
urpc/urpc1 13 l
...
urpc/urpc2 133 l
urpc/urpc2 136 l
urpc/urpc2 139 l
urpc/urpc2 142 l
urpc/urpc2 145 l

I have confirmed that the picture is in the right size:
identify 4.jpg              
4.jpg JPEG 640x192 640x192+0+0 8-bit sRGB 16.5KB 0.000u 0:00.000

But the problem is that when I run 

python train.py --dataset urpcDataset --data_path /media/kou/kou/monodepth3/urpc --split my_custom_split --model_name mono_640x192 --height 640 --width 192
Training model named:
   mono_640x192
Models and tensorboard events files are saved to:
   /home/kou/tmp
Training is using:
   cuda
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    trainer = Trainer(opts)
  File "/media/kou/kou/monodepth3/trainer.py", line 119, in __init__
    val_filenames = readlines(fpath.format("val"))
  File "/media/kou/kou/monodepth3/utils.py", line 17, in readlines
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/kou/kou/monodepth3/splits/my_custom_split/val_files.txt'

It seems that val_files.txt only needed in binocular video, right?

**Comment by kou5321** [comment]
And I have tried to use an empty val_files.txt, it turns out to be:

python train.py --dataset urpcDataset --data_path /media/kou/kou/monodepth3/urpc --split my_custom_split --model_name mono_640x192 --height 640 --width 192
Training model named:
   mono_640x192
Models and tensorboard events files are saved to:
   /home/kou/tmp
Training is using:
   cuda
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    trainer = Trainer(opts)
  File "/media/kou/kou/monodepth3/trainer.py", line 133, in __init__
    self.opt.frame_ids, 4, is_train=False, img_ext=img_ext)
  File "/media/kou/kou/monodepth3/datasets/mono_dataset.py", line 216, in __init__
    super(URPCDataset, self).__init__(*args, **kwargs)
  File "/media/kou/kou/monodepth3/datasets/mono_dataset.py", line 89, in __init__
    self.load_depth = self.check_depth()
  File "/media/kou/kou/monodepth3/datasets/mono_dataset.py", line 227, in check_depth
    line = self.filenames[0].split()
IndexError: list index out of range

I have also tried using a KITTI val_files.txt( from eigen zhou), it turns out to be:
 python train.py --dataset urpcDataset --data_path /media/kou/kou/monodepth3/urpc --split my_custom_split --model_name mono_640x192 --height 640 --width 192
Training model named:
   mono_640x192
Models and tensorboard events files are saved to:
   /home/kou/tmp
Training is using:
   cuda
frame_index:  1009
frame_index:  1274
frame_index:  232
frame_index:  1610
frame_index:  2349
frame_index:  1379
frame_index:  232
frame_index:  1312
frame_index:  271
frame_index:  224
frame_index:  68
frame_index:  26
frame_index:  1415
frame_index:  118
frame_index:  2445
frame_index:  237
frame_index:  220
frame_index:  4314
frame_index:  2636
frame_index:  482
frame_index:  631
frame_index:  720
frame_index:  2001
frame_index:  772
Using split:
   my_custom_split
There are 85 training items and 4424 validation items

Training
frame_index:  67
frame_index:  64
frame_index:  214
frame_index:  232
frame_index:  181
frame_index:  10
frame_index:  217
frame_index:  66
frame_index:  9
frame_index:  216
frame_index:  231
frame_index:  63
frame_index:  213
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    trainer.train()
  File "/media/kou/kou/monodepth3/trainer.py", line 187, in train
    self.run_epoch()
  File "/media/kou/kou/monodepth3/trainer.py", line 199, in run_epoch
    for batch_idx, inputs in enumerate(self.train_loader):
  File "/home/kou/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/kou/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/kou/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/kou/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/kou/kou/monodepth3/datasets/mono_dataset.py", line 162, in __getitem__
    inputs[("color", i, -1)] = self.get_color(folder, frame_index + i, side, do_flip)
  File "/media/kou/kou/monodepth3/datasets/mono_dataset.py", line 245, in get_color
    color = self.loader(self.get_image_path(folder, frame_index, side))
  File "/media/kou/kou/monodepth3/datasets/mono_dataset.py", line 24, in pil_loader
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/kou/kou/monodepth3/urpc/urpc1/66.jpg'

frame_index:  180


So I guess the val_files.txt must play an importtant role, but as to how it works, actuanlly I have no concept at all. Would you like to explain ti?

Many thanks in advance!

**Comment by daniyar-niantic** [comment]
Hi @kou5321 
The `train_files.txt` and `val_files.txt` specify which files belong to the training split and which files belong to the validation split. You need to have at least `batch_size` number of images in the validation split. During training it is important to monitor both the training and validation loss to avoid overfitting.
